# Generated by Django 6.1 on 2026-09-18 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True, max_length=1500)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('registration_open', 'Register open'), ('in_progress', 'In progress'), ('finished', 'Finished'), ('canceled', 'Canceled')], db_index=True, max_length=20)),
                ('location', models.CharField(blank=True, db_index=True, help_text='Provide the address, venue name, or link to the live stream', max_length=255)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_title', models.CharField(blank=True, editable=False, help_text='Historical name of the organization', max_length=255)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_events', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='event_ends_at_gte_starts_at'), models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'registration_open', 'in_progress', 'finished', 'canceled'])), name='event_status_valid_choice')],
            },
        ),
    ]
