# Generated by Django 6.1 on 2026-09-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('organizator', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.BooleanField(choices=[('RG', 'Register'), ('EN', 'Ending')], db_index=True, default='RG', max_length=2)),
                ('location', models.CharField(blank=True, db_index=True, help_text='Provide the address, venue name, or link to the live stream', max_length=255)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-starts_at'],
            },
        ),
    ]
