# Generated by Django 6.1 on 2026-09-17 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organization_title',
            field=models.CharField(blank=True, editable=False, help_text='Historical name of the organization', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_events', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[(None, 'Select the event status'), ('planned', 'Planned'), ('registration_open', 'Register open'), ('in_progress', 'In progress'), ('finished', 'Finished'), ('canceled', 'Canceled')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
