# Generated by Django 6.1 on 2026-09-28 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('place', 'Place'), ('nomination', 'Nomination'), ('participant', 'Participant')], db_index=True, default='participant', max_length=15)),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Numerical rank for place achievements (e.g. 1 for 1st place)', null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_achievements', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Achievement',
                'verbose_name_plural': 'Event Achievements',
                'ordering': ['kind', 'rank', 'title'],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['place', 'nomination', 'participant'])), name='event_achievement_kind_valid_choice'), models.CheckConstraint(condition=models.Q(('rank__gt', 0), ('rank__isnull', True), _connector='OR'), name='event_achievement_rank_positive'), models.UniqueConstraint(condition=models.Q(('kind', 'place')), fields=('event', 'rank'), name='unique_place_rank_per_event')],
            },
        ),
    ]
