# Generated by Django 6.1 on 2026-09-29 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participant Achievement',
                'verbose_name_plural': 'Participant Achievements',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='eventachievement',
            name='event_achievement_kind_valid_choice',
        ),
        migrations.AlterField(
            model_name='eventachievement',
            name='kind',
            field=models.CharField(choices=[('place', 'Place'), ('finalist', 'Finalist'), ('nomination', 'Nomination'), ('participation', 'Participation'), ('other', 'Other')], db_index=True, default='participation', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='eventachievement',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['place', 'finalist', 'nomination', 'participation', 'other'])), name='event_achievement_kind_valid_choice'),
        ),
        migrations.AddField(
            model_name='participantachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_achievements', to='events.eventachievement'),
        ),
        migrations.AddField(
            model_name='participantachievement',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_achievements', to='events.eventparticipant'),
        ),
        migrations.AddConstraint(
            model_name='participantachievement',
            constraint=models.UniqueConstraint(fields=('participant', 'achievement'), name='participant_achievement_unique'),
        ),
    ]
