# Generated by Django 6.1 on 2026-09-04 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userrefreshtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrefreshtoken',
            old_name='token',
            new_name='token_hash',
        ),
        migrations.AddField(
            model_name='userrefreshtoken',
            name='family_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='userrefreshtoken',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrefreshtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
